[window]
opacity = 1
decorations_theme_variant = "Dark" 
padding.x = 10
padding.y = 10
dimensions = { columns = 130, lines = 25 }
startup_mode = "Windowed"


[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "MediumItalic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "BoldItalic" }
size = 12
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }


[scrolling]
history = 10000
multiplier = 3


[terminal.shell]
program = "/usr/bin/zsh"


[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"


[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"


[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"


[keyboard]
bindings = [
  { key = "T", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "F11",  action = "ToggleFullscreen" },
]
